### ISSUE TITLE
Just installed newest version and it's not working

### ISSUE THREAD

**Issue by fizzlepop720** [StevensNJD4/LazyMan#11]
I had it working last night perfectly and followed the instructions to install the new one, removing the streamlink folder entirely and now I'm getting this:
-----
Streamlink starting...
[Streamlink for Windows v0.10.0 - Git b839cfd]
[cli][info] Found matching plugin hls for URL hlsvariant://<censored> verify=False
[cli][info] Available streams: 216p (worst), 288p, 360p, 504p, 540p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/57752703/kid/70054439 (HTTPSConnectionPool(host='mf.svc.nhl.com', port=443): Max retries exceeded with url: /ws/media/mf/v2.3/key/silk/mediaid/57752703/kid/70054439 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x060765F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)))
[cli][error] Try 1/1: Could not open stream <HLSStream('<censored>')> (No data returned from stream)
error: Could not open stream <HLSStream('<censored>')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
[End of Streamlink for Windows with ExitCode 1]

Streamlink done

**Comment by ltwbs** [comment]
I had the same issue, turns our Eset was blocking the ip/url.

**Comment by fizzlepop720** [comment]
Was it fixed?  I did the workaround and changed the entry in the hosts file and it's working now.. any need to change it back?

**Comment by welshy613** [comment]
Thanks for help pointing out IP
Only works for me with 188.240.208.152 and not 141.8.224.221

**Comment by StevensNJD4** [comment]
Fixed with latest version
