### ISSUE TITLE
Refresh doesn't work

### ISSUE THREAD

**Issue by tylerapplebaum** [StevensNJD4/LazyMan#22]
In the MLB tab, the games don't update if I click "Refresh". I have to go to the next day, then back, to see the updated feed or innings.

This is on version 2.3.1.20180418

**Comment by StevensNJD4** [comment]
Good catch! It will be fixed in the next 2.4 beta

**Comment by tylerapplebaum** [comment]
👍 Thanks!

**Comment by tylerapplebaum** [comment]
Fixed! Thanks so much!
