### ISSUE TITLE
Cannot resolve content-url

### ISSUE THREAD

**Issue by waituntilishake** [StevensNJD4/LazyMan#42]
I have been using Lazyman successfully since April. However, since last week I have not been able to open any streams. I can seem the various live games and I can open them, but once I try to select either the home or the away stream, I get an error message referring me to the log.
Additionally, when I try to open a previous game that I know I watched live (thus worked at one time), the stream looks like it is trying to open, but then doesn't. I have attached a tail of the log for each.
[livegame.log](https://github.com/StevensNJD4/LazyMan/files/3404598/livegame.log)
[previousgame.log](https://github.com/StevensNJD4/LazyMan/files/3404599/previousgame.log)

**Comment by StevensNJD4** [comment]
please post in the kodi addon repo
