### ISSUE TITLE
Cannot stream any games on Manjaro Linux

### ISSUE THREAD

**Issue by cain05** [StevensNJD4/LazyMan#48]
Version: 2.4.0.20190807

After the lastest big update for Manjaro Linux, LazyMan can no longer stream any NHL games.  Below is the error that I got the Leafs vs Caps game on Oct 16th.  The game tonight vs Boston is not working either, nor is any other game.  Works fine on Linux Mint and Windows 10.  The proxy is starting and doesn't give any errors.

```
-----
Streamlink starting...
[cli][info] Found matching plugin hls for URL hlsvariant://<censored> verify=False
error: Unable to open URL: <censored> (403 Client Error: Forbidden for url: http://hlslive-akc.med2.med.nhl.com/hdnts=exp=1571352029~acl=/*~id=nhlGatewayId:6919125~data=69499603~hmac=9c431869157952a83adb42183d6079e79dbf8103bddda5ef6061b5c75ac41908/f3435fd7eba0e7e0231d5bc971bb9dfe/ls03/nhl/2019/10/16/NHL_GAME_VIDEO_TORWSH_M2_VISIT_20191016_1570650184997/master_wired60.m3u8)

Streamlink done
```

**Comment by ransomts** [comment]
Hi, I am also running lazyman on manjaro. This is not an issue with lazyman but with the AUR package, please file a ticket [there.](https://aur.archlinux.org/packages/lazyman/)

In the meantime you can clone the repo and run the jar file directly with `java -jar LazyMan.jar`

**Comment by cain05** [comment]
I tested with the latest update as well and it seems to be working again.  Thanks for the update.
