### ISSUE TITLE
MACOS Catalina Issue - 

### ISSUE THREAD

**Issue by mlinton** [StevensNJD4/LazyMan#55]
I'm trying to install the application on macos catalina, and I successfully open and whitelist both the proxy and the lazyman.jar files.

I have confirmed that streamlink is installed with 'brew install streamlink'.

When attempting to open one of the games I get the following error.

![image](https://user-images.githubusercontent.com/2158650/72408976-a6cb2100-3721-11ea-8fe1-3eade597f0b2.png)

**Comment by mlinton** [comment]
Solved this myself - I had installed streamlink using homebrew and not easy_install like the docs suggest.  Reinstalled using easy_install and it now works.

**Comment by Mattrak** [comment]
Thanks! I get exactly the same results using vlc, but mpv works all the time. I will try the easy_install trick, although this command line is deprecated now, according to setuptools site?
[https://setuptools.readthedocs.io/en/latest/easy_install.html]()
