### ISSUE TITLE
Implement `start ongoing game from beginning` checkbox

### ISSUE THREAD

**Issue by kompot** [StevensNJD4/LazyMan#8]
https://www.reddit.com/r/NHLStreams/comments/4g9tep/how_to_stream_in_progress_game_from_the_beginning/

I've actually tested it and adding `--hls-live-edge=1000` as streamlink option started live stream 83 minutes before now. Knowing current time and game start time implementing option in question should be trivial.

**Comment by kompot** [comment]
More info on this: I've actually implemented in my home-grown yet-to-be-released-to-public NHL.TV streams downloader using a more advanced technique. Commit is here if you'd like to take a look
https://github.com/kompot/nhl-tv-geeky-streams/commit/9d0c0d813f491831d59f511fd9c87e28477cbe21#diff-efa3541214c54f09eee1267911fc4cfb

Key parts are:
- use latest streamlink (0.10 is still to come, so use master branch)
- it supports awesome feature https://streamlink.github.io/cli.html#cmdoption-hls-start-offset
- using it it's possible to rewind both live and archive streams and I use it to make streams download resumable (streamlink often drops connection and download just stops) and if match is live you are done ;( - it's not possible to continue watching where you've left off

That's actually a separate feature you might want to consider adding to lazyman. But i think it's totally worth it.

**Comment by StevensNJD4** [comment]
I will definitely add this

**Comment by StevensNJD4** [comment]
Added
